[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
transfer_hook_counter = "EBZDYx7599krFc4m2govwBdZcicr4GgepqC78m71nsHS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ikeyanagi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
